### ISSUE TITLE
automatically check dead links

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/docs#520]

**Comment by QuakeWang** [comment]
How is it going? Maybe we can use [markdown-link-check](https://github.com/tcort/markdown-link-check) to do this action : )

**Comment by alili** [comment]
sorry I’m late.

The problem was that there were some references to `localhost:4000` in the documentation, and these links, while dead, should not block compilation. 
This was an issue with older versions of vitepress, and it seems that the latest version of vitepress has a configuration item that handles this: [ignoreDeadLinks](https://vitepress.dev/reference/site-config#ignoredeadlinks). 
We shouldn't need to introduce new dependencies, but we should take the time to debug this configuration item to make sure it works. 

If you are willing to solve this problem, we are more than welcome.

**Comment by QuakeWang** [comment]
> sorry I’m late.
> 
> The problem was that there were some references to `localhost:4000` in the documentation, and these links, while dead, should not block compilation. This was an issue with older versions of vitepress, and it seems that the latest version of vitepress has a configuration item that handles this: [ignoreDeadLinks](https://vitepress.dev/reference/site-config#ignoredeadlinks). We shouldn't need to introduce new dependencies, but we should take the time to debug this configuration item to make sure it works.
> 
> If you are willing to solve this problem, we are more than welcome.

Markdown-link-check can support to add a `.dlc.json` in the root directory. Such as:

```json
{
    "ignorePatterns": [
      {
        "pattern": "^http://localhost"
      },
      {
        "pattern": "^https://twitter.com*"
      },
      {
        "pattern": "^http://192.168.xx.xx"
      },
      {
        "pattern": "^http://127.0.0.1"
      }
    ],
    "timeout": "10s",
    "retryOn429": true,
    "retryCount": 10,
    "fallbackRetryDelay": "1000s",
    "aliveStatusCodes": [
      200,
      401,
      403
    ]
  }
  ```
  
  This may skip some links like `localhost:4000`

**Comment by alili** [comment]
https://github.com/vuejs/vitepress/pull/2135

Fine-grained spell-checking is officially supported, which is weaker than Markdown-link-check, but seems to be sufficient. 

Thanks for your suggestion, It should be possible to introduce this plugin in other non-VitePress projects.
